name: Simple CI Pipeline

on:
  push:
    branches: [ "master" ]
         

jobs:
  build:
    runs-on: ubantu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run a simple command
      run: echo "This is my automated pipeline run 1"
              